### ISSUE TITLE
Page "modification info" : amélioration de la page

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/espace-membre-next#100]
- [x] "Adresse du profil LinkedIn" => c'est pas que Linkedin je crois, certaines personnes ont mis leur site perso
- [ ] Sur les missions, je pense qu'il faudrait mettre les plus récentes en premier. Et voir même cacher les anciennes dans un accordéon (plus de raison de les modifier)
- [x] Quand on enregistre, ça reste en bas de l'écran. On ne voit donc pas le message "La PR a été créée". Je pense qu'il faudrait revenir en haut de la page
- [ ] Pour les personnes transverses, ça serait chouette de pouvoir aussi renseigner notre équipe (team/...) et pas que un produit

**Comment by revolunet** [comment]
a priori tout est réglé sauf la gestion de la team ? a définir dans une autre issue
