### ISSUE TITLE
Correction sur la Liste d'attente

### ISSUE THREAD

**Issue by astranchet** [betagouv/espace-membre-next#166]
![image](https://github.com/betagouv/espace-membre-next/assets/1374389/0bd02181-3655-405b-a994-f2ffe0c58b26)

J'identifie 2 problèmes : 
- une typo (manque le e à Liste d'attent**e**)
- le terme Liste d'attente qui apparaît trop de fois. 

+ une proposition : 
faire apparaître "Sur liste d'attente" comme un badge (comme e-learning) plutôt que dans le titre

**Comment by revolunet** [comment]
a priori ca a été corrigé

**Comment by astranchet** [comment]
La typo est toujours là et fait pleurer mes petits yeux

**Comment by revolunet** [comment]
D'après moi ca vient de airtable

<img width="284" alt="Capture d’écran 2024-05-22 à 09 07 30" src="https://github.com/betagouv/espace-membre-next/assets/124937/c4301ba0-808f-4bee-acb4-70cee9a70b30">

**Comment by astranchet** [comment]
Oui, mais cette mention n'est pas rajoutée à la main mais par du code. Je veux bien déplacer l'issue, mais dans quel répo ?

**Comment by revolunet** [comment]
peut-être dans les scripts airtable, mais je n'ai pas trouvé

**Comment by astranchet** [comment]
Merci du tip, trouvé et corrigé : https://airtable.com/appebTa6XsY6fDixm/wflIVzhZU6n6k68VC/wachF7zFZEJGbwfUW
