### ISSUE TITLE
Les redirections emails ne sont plus affiché dans la fiche membre

### ISSUE THREAD

**Issue by jdauphant** [betagouv/espace-membre-next#17]
## Nouvelle interface
![image](https://github.com/betagouv/espace-membre-next/assets/1238254/bc98ec83-64f4-4126-a58f-f67c4f2c0a91)
## Ancienne interface
![image](https://github.com/betagouv/espace-membre-next/assets/1238254/f9c17776-ee48-462b-9190-aec3ffc9581d)

Je prends l'exemple de thibault. Cela pose problème pour dépanner les gens.

**Comment by astranchet** [comment]
Pourrait être corriger avec le redesign de la fiche membre



![Image](https://github.com/user-attachments/assets/6c855cdc-95da-424c-8ffa-937e5ab71912)
