### ISSUE TITLE
Pimp de la page d'accueil

### ISSUE THREAD

**Issue by astranchet** [betagouv/espace-membre-next#173]
Proposition un peu plus visuelle pour la page d'accueil : 

![Home](https://github.com/betagouv/espace-membre-next/assets/1374389/3ecdb9eb-674f-4cf2-842b-527dcdc9586f)

Maquette dispo sur : https://www.figma.com/file/x9WPm0W8pdCxrXkb1T6FQ3/Secre%CC%81tariat?type=design&node-id=1612%3A6438&mode=dev&t=OnJ0AtSuL06zQbGk-1

**Comment by marinepurson2** [comment]
Trop trop bien ! Du coup je relance le débat : est-ce qu'on veut transformer le nom en Espace communauté ?

**Comment by astranchet** [comment]
Je te suivrais si tu veux lancer ce combat, mais j'ai pleins de questions : 
- Est-ce qu'on le fait en douce ? ou on communique dessus ?
- Est-ce qu'il y a d'autres choses que le code et la doc à modifier ? (genre des messages de descriptions dans Mattermost) ?
- Est-ce qu'on modifie aussi l'URL ? 

Bref, c'est pas anodin, il faudrait se poser un peu pour faire un plan si on y va !
