### ISSUE TITLE
Pimp de l'espace membre connecté

### ISSUE THREAD

**Issue by astranchet** [betagouv/espace-membre-next#174]
Page d'accueil de l'espace membre : 

![Connecté](https://github.com/betagouv/espace-membre-next/assets/1374389/6bc43511-be97-44cf-957b-d76177c67886)

Maquette sur Figma : https://www.figma.com/file/x9WPm0W8pdCxrXkb1T6FQ3/Secre%CC%81tariat?type=design&node-id=1612%3A6445&mode=dev&t=OnJ0AtSuL06zQbGk-1

**Comment by AmelAlili** [comment]
😍

**Comment by marinepurson2** [comment]
Waaaaah ! C'est vraiment trop bien !

3 retours : 
- L'observatoire de la communauté irait plutôt dans la partie "Explorer la communauté" pour moi
- Pour harmoniser avec les autres tuiles où tout est sous forme de verbe d'action, je mettrais "Consulter des informations anonymisées sur la communauté" dans la tuile "Observatoire de la communauté"
- J'ai un doute sur la tuile "Fiche produit" : est-ce qu'on veut permettre de modifier la fiche produit de la personne (auquel cas j'ai l'impression que ça irait plutôt dans "Mon compte") ? Ou est-ce qu'on veut permettre de consulter les fiches produits ?

**Comment by astranchet** [comment]
> L'observatoire de la communauté irait plutôt dans la partie "Explorer la communauté" pour moi

"Observatoire de la communauté", aujourd'hui, ce sont les questions anonymes pour le remplir. Mais oui, le lien vers le tableau Metabase pour l'explorer devrait être dans la partie "Explorer", je suis en phase.

> Pour harmoniser avec les autres tuiles où tout est sous forme de verbe d'action, je mettrais "Consulter des informations anonymisées sur la communauté" dans la tuile "Observatoire de la communauté"

Je trouvais ça trop verbeux et incompréhensible pour le proposer ; mais la non harmonisation me dérange aussi 😅. Peut être un truc genre "Explorer la composition de la communauté" ? 

> J'ai un doute sur la tuile "Fiche produit" : est-ce qu'on veut permettre de modifier la fiche produit de la personne (auquel cas j'ai l'impression que ça irait plutôt dans "Mon compte") ? Ou est-ce qu'on veut permettre de consulter les fiches produits ?

Je me suis posé la même question... Aujourd'hui, on peut modifier toutes les fiches produits (contrairement aux fiches membres), mais je voulais garder la section Compte pour les parties "personnelles"

**Comment by marinepurson2** [comment]
Top ! 

- Pour l'Observatoire, on pourrait mettre : Consulter des informations sur la composition de la communauté
- Pour la tuile "Fiche produit", dans ce cas, ça pourrait être : Consulter et modifier les fiches produits

**Comment by astranchet** [comment]
[Nouvelle version](https://www.figma.com/file/x9WPm0W8pdCxrXkb1T6FQ3/Espace-Membre?type=design&node-id=1612%3A6445&mode=dev&t=Jo2oHRRzgXBBjRV0-1) du coup : 

![Image](https://github.com/betagouv/espace-membre-next/assets/1374389/f5fb2cbd-1b3b-4aab-8901-10f23b82b5f1)
