### ISSUE TITLE
ETQ membre, je consulte fiche d'un autre membre où sont mises en avant ses infos métiers et de contact

### ISSUE THREAD

**Issue by astranchet** [betagouv/espace-membre-next#186]
Proposition pour la fiche membre pour **mettre en avant les infos métiers et de contact** (plus que les informations techniques)**  : 
![Proposition Fiche membre](https://github.com/betagouv/espace-membre-next/assets/1374389/2e5b12ae-0907-4e99-95f7-ca8be4c55c51)

@AmelAlili @fannyblanc @marinepurson2 ça vous paraît intéressant pour encourager le remplissage des fiches ?

**Comment by sneko** [comment]
@astranchet as-tu eu un retour de l'équipe pour savoir si on part là-dessus ?

**Comment by astranchet** [comment]
Juste de @revolunet qui était chaud je crois. Moi je serai partante d'y aller, et d'améliorer dans un 2ème temps

**Comment by marinepurson2** [comment]
Hello, j'avais pas vu, désolée ! 

Statut du compte, ça correspond à quoi @astranchet ?

**Comment by marinepurson2** [comment]
Ca me semble super
