### ISSUE TITLE
le champs "employeur" n'est pas modifiable 

### ISSUE THREAD

**Issue by Tibo-aplus** [betagouv/espace-membre-next#19]
![image](https://github.com/betagouv/espace-membre-next/assets/56031969/847df17d-2c7f-430a-a911-8a988851288b)

le champs "employeur" n'est pas modifiable lorsque l'on clique sur 
![image](https://github.com/betagouv/espace-membre-next/assets/56031969/ada49813-d21d-450f-b2ee-9056ff0117e5)

Sur cette page https://espace-membre.incubateur.net/account

**Comment by revolunet** [comment]
Ici je pense qu'il faudrait pouvoir éditer les différentes "missions"

**Comment by revolunet** [comment]
ca devrait être réglé avec #52

**Comment by revolunet** [comment]
fixé par #52
