### ISSUE TITLE
ETQ membre je visualise a carte intégrée avec le footer et le header du DSFR

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#211]
voir si on peut mieux intégrer la map

https://github.com/betagouv/espace-membre-next/blob/main/src/app/(private)/(dashboard)/map/route.js

**Comment by sneko** [comment]
@revolunet qu'entends-tu par "mieux l'intégrer" ? Est-ce le fait d'avoir le header/footer du site qui l'englobe ? ou dans l'idée changer la logique d'affichage de https://espace-membre.incubateur.net/map ?

**Comment by sneko** [comment]
@astranchet le fait d'intégrer le header/footer du DSFR ferait que la carte serait plus difficilement utilisable sur mobile (leur version n'est pas adaptée pour le contenu full page). As-tu une idée ?

**Comment by astranchet** [comment]
Sur [Cartographie des lieux d'inclusions](https://cartographie.societenumerique.gouv.fr/cartographie), ils ont une sorte de switch carte/version texte. Mais nous, on a zéro information textuelles (ce qui est un problème en terme d'accessibilité)

Nous, on voudrait simplement : 
- une version réduite du header sur mobile (ça c'est possible)
- le footer qui apparaît sous la carte tout simplement
