### ISSUE TITLE
Fix: empecher de mettre un email en majuscule, ça fait planter la connexion

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/espace-membre-next#228]

**Comment by sneko** [comment]
Plutôt que de l'empêcher, on pourrait juste transformer la valeur en lowercase (avec bien entendu la vérification d'un email valide)

**Comment by LucasCharrier** [comment]
yes c'est ce que j'ai fait dans le fix: https://github.com/betagouv/espace-membre-next/pull/229/files
