### ISSUE TITLE
Eviter les PR vides

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#25]
Parfois les PR soumises sont vides : https://github.com/betagouv/beta.gouv.fr/pull/17705
```[tasklist]
### Tasks
- [x] Fiche produit
- [x] Fiche membre : https://github.com/betagouv/espace-membre-next/pull/89
```

**Comment by LucasCharrier** [comment]
Je crois avoir compris d'où vienne les PRs vides. Il semble que juste en visitant le page produit, le formulaire est envoyé, ça doit être un soucis à cause de la balise form, si on presse "entré" le formulaire est envoyé. Je peux prendre.

**Comment by revolunet** [comment]
Ok... Ça peut arriver aussi pour les fiches membres mais ça devrait être réglé avec mes prochains fixes sur le formulaire

**Comment by LucasCharrier** [comment]
ok, j'ai fait des fix pour la page produit. Je ne touche pas à la page membre du coup.
