### ISSUE TITLE
[bug] Page d'erreur pas très compréhensible

### ISSUE THREAD

**Issue by astranchet** [betagouv/espace-membre-next#251]
J'ai essayé de me connecter avec as.tranchet@gmail.com

J'ai reçu un email de connexion : Ou utiliser ce lien :
https://espace-membre-staging.osc-fr1.scalingo.io/api/auth/callback/email?callbackUrl=https%3A%2F%2Fespace-membre-staging.osc-fr1.scalingo.io%2Flogin&token=0991050a77fe17478c61f3eb4e3f08dfaf7f5ba7d02d1486931ebc4cb8cb4e01&email=as.tranchet%40gmail.com

Qui m'a emmené sur cette URL : https://espace-membre-staging.osc-fr1.scalingo.io/verify 

qui a affiché une erreur "TypeError : d is undefined"

![Image](https://github.com/betagouv/espace-membre-next/assets/1374389/6433eefa-9947-4e7b-9fa2-1b73f8af0a1c)

- [x] Corriger le problème de fond
- [x] Améliorer la page d'erreur pour plutôt mettre en titre "Erreur", et éventuellement plus loin le message.

**Comment by LucasCharrier** [comment]
Ok, c'était une erreur spécifique à ce compte, où il y a 0 mission. J'ai fait en sorte de pas afficher d'erreur si le compte à 0 missions mais ça ne devrait pas arriver avec des nouveaux utilisateurs.
