### ISSUE TITLE
gestion des erreurs page /update

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#364]
Lorsque fanny essaie de modifier ma fiche via la page "/update", ca lui envoie un message comme quoi c'est modifié mais en fait non 🤔 

Cette feature serait utile pour l'équipe animation et les respopos

**Comment by LucasCharrier** [comment]
Pour ma part ça fonctionne de mon côté et un message d'erreur semble bien envoyé le cas échéant. Il manquait un await, c'est ce qui aurait pu créer expliquer que le retour ui soit success sans avoir faire l'update.
