### ISSUE TITLE
ETQ je peux ajouter ou supprimer une image sur une fiche produit

### ISSUE THREAD

**Issue by AmelAlili** [betagouv/espace-membre-next#39]
Actuellement, il n'y a pas de possibilité de supprimer l'image de la fiche produit sur l'espace membre.
![image](https://github.com/betagouv/espace-membre-next/assets/113687868/716eef3a-94aa-4984-aed0-4434bbf5c1bd)
conséquence: la nouvelle image ne peut être ajoutée et aucune information est donnée

_**Suggestions:**_
- Ajouter un bouton de suppression
- Afficher l'aperçu de l'image actuellement présente sur sa fiche (pour ne pas avoir à passer par le site beta.gouv.fr pour vérifier)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/espace-membre-next/issues/103
```

**Comment by revolunet** [comment]
En regardant un peu je vois qu'on est [tres souples](https://github.com/betagouv/beta.gouv.fr/blob/master/_includes/hero-startup.html#L3) sur l'image qui est utilisée pour les SE donc aujourd'hui on ne sait pas prédire l'image à afficher 😢

**Comment by revolunet** [comment]
Il faut faire #103 avant 😬

**Comment by revolunet** [comment]
oui mais il faut attendre le refacto côté fiches imho
