### ISSUE TITLE
beadcrumbs et navigation

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#578]
Je vois plusieurs pistes possibles d'amélioration, à discuter, on pourra splitter en plusieurs issues s'il y a des trucs à en tirer:

### Menu

Exemple:

  - Accueil
  - Communauté
     - Ma fiche
     - Les membres
     - Carte des membres
     - Observatoire
     - Bubbles
  - Fiches
    - produits
    - incubateurs
    - équipes
    - organisations (sponsors)
  - Formations
  - Évènements
  - Infolettres
  - Admin?
    
### Breadcrumbs

Je pense qu'il faut revoir le fonctionnement, peut-être avec une liste à plat explicite des routes qu'on veut couvrir ?

### Sidebar

Elle prend beaucoup de place je trouve :/ Un bon menu + breadcrumbs ne suffirait pas ?

**Comment by astranchet** [comment]
Amen pour la sidebar. C'est un reste de résidu de la version d'avant pour simplifier la migration, mais je la trouve très embêtante aussi.

Et assez raccord aussi sur la hiérarchie. On pourrait simplifier le menu et harmoniser avec un truc plus ou moins comme ça : 
![image](https://github.com/user-attachments/assets/7a6ff385-4760-4053-b50d-3d4a126a1d51)
