### ISSUE TITLE
renouvellement de badge : crash

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#61]
Il semblerait que quand on coche la case pour renouveler son badge, cela crash l'application backend

![Image](https://github.com/betagouv/espace-membre-next/assets/124937/5207ccfd-5fbd-4a25-a7ad-cde93d8074d4)

**Comment by LucasCharrier** [comment]
Il manquait la variable DS_DEMARCHE_RENEWAL_NUMBER dans les env var
