### ISSUE TITLE
Mise à jour des fiches par respopos/respos incubateurs

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#614]
(régression suite départ de GH)

Certains incubateurs souhaitent pouvoir modifier les fiches des leurs membres et produits.

Il faudrait donc leur afficher la possibilité de modifier les données qui les concernent.

La première étape serait pour nous de définir quels rôles ont droit de modification et sur quelles données (matrice des droits)

Roles:
 - respo incubateur: écriture membres et produits fabrique
 - respopo : écriture membres et produits

**Comment by LucasCharrier** [comment]
@revolunet je ne comprends pas quels distinctions tu fais entre les droits respo incubateur et respopo ?

Sinon pour les accès on peut avoir un object avec les accès par incubateur :

{
 dinum: ['nom.prenomrespopop', 'nom2.prenom2'],
 masaf: ['nom3.prenom3']
}

Et on se base la-dessus pour voir si la personne à le droit d'éditer ou non.

**Comment by revolunet** [comment]
oui je pense que ça suffirait par incubateur avec une liste d'username associés
