### ISSUE TITLE
champs à ajouter dans la fiche produit

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#672]
On aimerait savoir en plus:
 - si un produit a une URL non publique (ex: signaux faibles) VS une URL non renseignée (ex: nouvelles SE)
 - si le produit est aussi une application mobile. il y a parfois une URL "vitrine" en plus d'apps mobiles

**Comment by astranchet** [comment]
On avait parlé de différentier mesure d'impact et stats aussi ?
